package freeling

var ER_MUTANTS = map[string]string{
	"abstraer":     "abstraj",
	"abstener":     "abstuv",
	"anteponer":    "antepus",
	"atraer":       "atraj",
	"atener":       "atuv",
	"autocontener": "autocontuv",
	"bienquerer":   "bienquis",
	"componer":     "compus",
	"contrahacer":  "contrahic",
	"contraer":     "contraj",
	"contraponer":  "contrapus",
	"contener":     "contuv",
	"caber":        "cup",
	"deponer":      "depus",
	"descomponer":  "descompus",
	"desfacer":     "desfic",
	"deshacer":     "deshic",
	"desquerer":    "desquis",
	"detraer":      "detraj",
	"detener":      "detuv",
	"disponer":     "dispus",
	"distraer":     "distraj",
	"entretener":   "entretuv",
	"exponer":      "expus",
	"extraer":      "extraj",
	"hacer":        "hic",
	"haber":        "hub",
	"imponer":      "impus",
	"indisponer":   "indispus",
	"interponer":   "interpus",
	"licuefacer":   "licuefic",
	"malquerer":    "malquis",
	"maltraer":     "maltraj",
	"mantener":     "mantuv",
	"manutener":    "manutuv",
	"obtener":      "obtuv",
	"oponer":       "opus",
	"posponer":     "pospus",
	"predisponer":  "predispus",
	"preponer":     "prepus",
	"presuponer":   "presupus",
	"proponer":     "propus",
	"poder":        "pud",
	"poner":        "pus",
	"querer":       "quis",
	"rarefacer":    "rarefic",
	"recomponer":   "recompus",
	"rehacer":      "rehic",
	"reponer":      "repus",
	"retraer":      "retraj",
	"retrotraer":   "retrotraj",
	"retener":      "retuv",
	"satisfacer":   "satisfic",
	"sobreexponer": "sobreexpus",
	"sobreponer":   "sobrepus",
	"sostener":     "sostuv",
	"substraer":    "substraj",
	"saber":        "sup",
	"superponer":   "superpus",
	"suponer":      "supus",
	"sustraer":     "sustraj",
	"traer":        "traj",
	"transponer":   "transpus",
	"trasponer":    "traspus",
	"tener":        "tuv",
	"vr":           "vi",
	"yuxtaponer":   "yuxtapus",
}

var ER_MUTANT_TAG27_TO_SUFFIXES = map[string][]string{
	"IS1S0": {"e"},
	"IS1P0": {"imos"},
	"IS2S0": {"iste"},
	"IS2P0": {"isteis"},
	"IS3S0": {"o"},
	"IS3P0": {"ieron"},
	"SI1S0": {"iera", "iese"},
	"SI1P0": {"iéramos", "iésemos"},
	"SI2S0": {"ieras", "ieses"},
	"SI2P0": {"ierais", "ieseis"},
	"SI3S0": {"iera", "iese"},
	"SI3P0": {"ieran", "iesen"},
	"SF1S0": {"iere"},
	"SF1P0": {"iéremos"},
	"SF2S0": {"ieres"},
	"SF2P0": {"iereis"},
	"SF3S0": {"iere"},
	"SF3P0": {"ieren"},
}
