package freeling

var IR_MUTANTS = map[string]string{
	"aducir":      "aduj",
	"advenir":     "advin",
	"antedecir":   "antedij",
	"antevenir":   "antevin",
	"avenir":      "avin",
	"bendecir":    "bendij",
	"condecir":    "condij",
	"conducir":    "conduj",
	"contradecir": "contradij",
	"contravenir": "contravin",
	"convenir":    "convin",
	"deducir":     "deduj",
	"desavenir":   "desavin",
	"desconvenir": "desconvin",
	"desdecir":    "desdij",
	"devenir":     "devin",
	"decir":       "dij",
	"disconvenir": "disconvin",
	"entredecir":  "entredij",
	"ir":          "fu",
	"inducir":     "induj",
	"intervenir":  "intervin",
	"introducir":  "introduj",
	"maldecir":    "maldij",
	"pudrir":      "podr",
	"predecir":    "predij",
	"prevenir":    "previn",
	"producir":    "produj",
	"provenir":    "provin",
	"reconducir":  "reconduj",
	"reconvenir":  "reconvin",
	"redecir":     "redij",
	"reducir":     "reduj",
	"reproducir":  "reproduj",
	"revenir":     "revin",
	"seducir":     "seduj",
	"sobrevenir":  "sobrevin",
	"subvenir":    "subvin",
	"supervenir":  "supervin",
	"traducir":    "traduj",
	"venir":       "vin",
}

var IR_MUTANT_TAG_TO_SUFFIX = map[string]string{
	"VMIS1S0": "e",
	"VMIS1P0": "imos",
	"VMIS2S0": "iste",
	"VMIS2P0": "isteis",
	"VMIS3S0": "o",
	"VMIS3P0": "ieron",
	"VMSI1S0": "iera",
	"VMSI1P0": "iéramos",
	"VMSI2S0": "ieras",
	"VMSI2P0": "ierais",
	"VMSI3S0": "iera",
	"VMSI3P0": "ieran",
	"VMSF1S0": "iere",
	"VMSF1P0": "iéremos",
	"VMSF2S0": "ieres",
	"VMSF2P0": "iereis",
	"VMSF3S0": "iere",
	"VMSF3P0": "ieren",
}
