package freeling

var IR_TAG_TO_SUFFIXES = map[string][]string{
	"VMIS1S0": {"í"},
	"VMIS1P0": {"imos"},
	"VMIS2S0": {"iste"},
	"VMIS2P0": {"isteis"},
	"VMIS3S0": {"ió"},
	"VMIS3P0": {"ieron"},
	"VMIC1S0": {"iría"},
	"VMIC1P0": {"iríamos"},
	"VMIC2S0": {"irías"},
	"VMIC2P0": {"iríais"},
	"VMIC3S0": {"iría"},
	"VMIC3P0": {"irían"},
	"VMIF1S0": {"iré"},
	"VMIF1P0": {"iremos"},
	"VMIF2S0": {"irás"},
	"VMIF2P0": {"iréis"},
	"VMIF3S0": {"irá"},
	"VMIF3P0": {"irán"},
	"VMII1S0": {"ía"},
	"VMII1P0": {"íamos"},
	"VMII2S0": {"ías"},
	"VMII2P0": {"íais"},
	"VMII3S0": {"ía"},
	"VMII3P0": {"ían"},
	"VMIP1S0": {"o"},
	"VMIP1P0": {"imos"},
	"VMIP2S0": {"es"},
	"VMIP2P0": {"ís"},
	"VMIP3S0": {"e"},
	"VMIP3P0": {"en"},
	"VMN0000": {"ir"},
	"VMG0000": {"iendo"},
	"VMP00SM": {"ido"},
	"VMP00SF": {"ida"},
	"VMP00PM": {"idos"},
	"VMP00PF": {"idas"},
	"VMSP1S0": {"a"},
	"VMSP1P0": {"amos"},
	"VMSP2S0": {"as"},
	"VMSP2P0": {"áis"},
	"VMSP3S0": {"a"},
	"VMSP3P0": {"an"},
	"VMM01P0": {"amos"},
	"VMM02S0": {"e"},
	"VMM02P0": {"id"},
	"VMM03S0": {"a"},
	"VMM03P0": {"an"},
	"VMSI1S0": {"iera", "iese"},
	"VMSI1P0": {"iéramos", "iésemos"},
	"VMSI2S0": {"ieras", "ieses"},
	"VMSI2P0": {"ierais", "ieseis"},
	"VMSI3S0": {"iera", "iese"},
	"VMSI3P0": {"ieran", "iesen"},
	"VMSF1S0": {"iere"},
	"VMSF1P0": {"iéremos"},
	"VMSF2S0": {"ieres"},
	"VMSF2P0": {"iereis"},
	"VMSF3S0": {"iere"},
	"VMSF3P0": {"ieren"},
}
