package freeling

var IR_VMP_STEMS = map[string][]string{
	"abrir":         {"abiert"},
	"adscribir":     {"adscrit"},
	"antedecir":     {"antedich"},
	"astringir":     {"astrict", "astringid"},
	"bendecir":      {"bendit"},
	"circunscribir": {"circunscrit"},
	"condecir":      {"condich"},
	"contradecir":   {"contradich"},
	"cubrir":        {"cubiert"},
	"desabrir":      {"desabiert"},
	"describir":     {"descrit"},
	"descubrir":     {"descubiert"},
	"desdecir":      {"desdich"},
	"decir":         {"dich"},
	"embair":        {"embaíd", "embaid"},
	"encubrir":      {"encubiert"},
	"entreabrir":    {"entrabiert"},
	"entredecir":    {"entredich"},
	"escribir":      {"escrit"},
	"imprimir":      {"impres"},
	"inscribir":     {"inscrit"},
	"maldecir":      {"maldich"},
	"manuscribir":   {"manuscrit"},
	"morir":         {"muert"},
	"oprimir":       {"opres", "oprimid"},
	"pudrir":        {"podrid"},
	"predecir":      {"predich"},
	"premorir":      {"premuert"},
	"prescribir":    {"prescript", "prescrit"},
	"proscribir":    {"proscrit"},
	"prostituir":    {"prostitut", "prostituid"},
	"reabrir":       {"reabiert"},
	"reasumir":      {"reasunt", "reasumid"},
	"recubrir":      {"recubiert"},
	"redescubrir":   {"redescubiert"},
	"redecir":       {"redich"},
	"reelegir":      {"reelect", "reelegid"},
	"reescribir":    {"reescrit"},
	"reimprimir":    {"reimpres", "reimprimid"},
	"repudrir":      {"repodrid"},
	"requerir":      {"requisit", "requerid"},
	"rescribir":     {"rescrit"},
	"sobreescribir": {"sobreescrit"},
	"subscribir":    {"subscrit"},
	"suscribir":     {"suscrit"},
	"transcribir":   {"transcrit"},
	"trascribir":    {"trascrit"},
}
