#!/bin/bash -ex

cd $(dirname $0)/..

pushd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
popd
go install -v bitbucket.org/danstutzman/language-learning-go/...

mkdir -p db/1_parses
DB_PATH=db/db.sqlite3 \
  GOOGLE_TRANSLATE_API_KEY=`cat ~/.google_translate_api_key` \
  $GOPATH/bin/parse-phrases db/1_phrases.yaml "$@"
