#!/bin/bash -ex

cd $(dirname $0)/..

pushd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
go install -v bitbucket.org/danstutzman/language-learning-go/...
popd

mkdir -p db/1_parses
DB_PATH=db/db.sqlite3 \
  PYTHON3_PATH=$(which python3) \
  $GOPATH/bin/parse-corpus db/corpora/simplest.txt "$@"
  #$GOPATH/bin/parse-corpus db/corpora/beginner-sentences.txt "$@"
  #$GOPATH/bin/parse-corpus db/corpora/advanced-verbs.txt "$@"
  #$GOPATH/bin/parse-corpus db/corpora/spanish-in-texas.txt "$@"
  #$GOPATH/bin/parse-corpus db/corpora/conjugations.txt "$@"
  #$GOPATH/bin/parse-corpus db/corpora/nouns.csv "$@"
  #$GOPATH/bin/parse-corpus db/corpora/spanishpod.yaml "$@"

