#!/bin/bash -ex

cd `dirname $0`/..

sqlite3 db/db.sqlite3 <<EOF

DROP TABLE IF EXISTS morphemes;
CREATE TABLE morphemes (
  id                INTEGER PRIMARY KEY NOT NULL,
  type              TEXT NOT NULL,
  l2                TEXT NOT NULL,
  lemma             TEXT, -- type=VERB_SUFFIX has no lemma
  freeling_tag      TEXT,
  verb_category     TEXT,
  tense             TEXT -- only for VERB_STEM_CHANGE
);

INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'está', 'estar', 'VMIP3S0', NULL);
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'estoy', 'estar', 'VMIP1S0', NULL);
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'soy', 'ser', 'VSIP1S0', NULL);
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'soy', 'ser', 'VSIP1S0', NULL);
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'eres', 'ser', 'VSIP2S0', NULL);
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_UNIQUE', 'tengo', 'tener', 'VMIP1S0', NULL);

INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category, tense)
  VALUES ('VERB_STEM_CHANGE', 'estuv-', 'estar', NULL, NULL, 'past');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category, tense)
  VALUES ('VERB_STEM_CHANGE', 'tuv-', 'tener', NULL, NULL, 'past');

INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-ar', NULL, 'VMN0000', 'ar');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-er', NULL, 'VSN0000', 'er');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-a', NULL, 'VMIP3S0', 'ar');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-án', NULL, 'VMIP3P0', 'ar');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-amos', NULL, 'VMIP1P0', 'ar');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-e', NULL, 'VMIS1S0', 'er');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-e', NULL, 'VMIP3S0', 'er');
INSERT INTO morphemes (type, l2, lemma, freeling_tag, verb_category)
  VALUES ('VERB_SUFFIX', '-e', NULL, 'VMIS1S0', 'stempret');

EOF
