#!/bin/bash -ex

cd $(dirname $0)/..

pushd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
go install -v bitbucket.org/danstutzman/language-learning-go/...
popd

sqlite3 db/db.sqlite3 <<EOF
DROP TABLE IF EXISTS cards;
CREATE TABLE cards (
  id                INTEGER PRIMARY KEY NOT NULL,
  is_sentence       BOOLEAN NOT NULL,
  type              TEXT NOT NULL,
  l2                TEXT NOT NULL,
  l1                TEXT NOT NULL,
  mnemonic12        TEXT,
  mnemonic21        TEXT,
  morpheme_ids_csv  TEXT NOT NULL
);
CREATE INDEX idx_cards_l2 ON cards(l2);

DROP TABLE IF EXISTS cards_morphemes;
CREATE TABLE cards_morphemes (
  card_id      INTEGER NOT NULL,
  morpheme_id  INTEGER NOT NULL,
  num_morpheme INTEGER NOT NULL,
  begin        INTEGER NOT NULL
);
CREATE INDEX idx_cards_morphemes_card_id ON cards_morphemes(card_id);
CREATE INDEX idx_cards_morphemes_morpheme_id ON cards_morphemes(morpheme_id);

DROP TABLE IF EXISTS answers;
CREATE TABLE answers (
  id              INTEGER PRIMARY KEY NOT NULL,
  type            TEXT NOT NULL,
  card_id         INTEGER NOT NULL,
  expectation     TEXT NOT NULL,

  shown_at         DATETIME NOT NULL,
  answered_l1      TEXT,
  answered_l2      TEXT,
  showed_mnemonic  BOOLEAN NOT NULL,
  first_key_millis INTEGER NOT NULL,
  last_key_millis  INTEGER NOT NULL
);

DROP TABLE IF EXISTS answer_morphemes;
CREATE TABLE answer_morphemes (
  id          INTEGER PRIMARY KEY NOT NULL,
  answer_id   INTEGER NOT NULL,
  morpheme_id INTEGER NOT NULL,
  shown_at    DATETIME NOT NULL,
  correct_l2  TEXT,
  aligned_l2  TEXT
);
CREATE INDEX idx_answer_morphemes_answer_id ON answer_morphemes(answer_id);
CREATE INDEX idx_answer_morphemes_morpheme_id ON answer_morphemes(morpheme_id);

EOF

#$GOPATH/bin/load-noun-cards db/corpora/nouns.csv db/db.sqlite3
#$GOPATH/bin/load-corpus-into-cards db/corpora/spanishpod.yaml db/db.sqlite3
#$GOPATH/bin/load-corpus-into-cards db/corpora/conjugations.txt db/db.sqlite3
#$GOPATH/bin/load-corpus-into-cards db/corpora/advanced-verbs.txt \
#$GOPATH/bin/load-corpus-into-cards db/corpora/beginner-sentences.txt \
$GOPATH/bin/load-corpus-into-cards db/corpora/simplest.csv \
  db/db.sqlite3 \
  "/Users/dan/Documents/language learning resources/spanish/anki-decks/dictionary/dictionary.csv"
