#!/bin/bash -ex

cd $(dirname $0)/..

pushd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
popd
go install -v bitbucket.org/danstutzman/language-learning-go/...

sqlite3 db/db.sqlite3 <<EOF
DROP TABLE IF EXISTS cards;
CREATE TABLE cards (
  id                INTEGER PRIMARY KEY NOT NULL,
  type              TEXT NOT NULL,
  l2                TEXT NOT NULL,
  mnemonic21        TEXT,
  morpheme_ids_csv  TEXT NOT NULL,
  noun_gender       TEXT
);
CREATE INDEX idx_cards_l2 ON cards(l2);

DROP TABLE IF EXISTS cards_morphemes;
CREATE TABLE cards_morphemes (
  card_id      INTEGER NOT NULL,
  morpheme_id  INTEGER NOT NULL,
  num_morpheme INTEGER NOT NULL
);
CREATE INDEX idx_cards_morphemes_card_id ON cards_morphemes(card_id);
CREATE INDEX idx_cards_morphemes_morpheme_id ON cards_morphemes(morpheme_id);

DROP TABLE IF EXISTS challenges;
CREATE TABLE challenges (
  id              INTEGER PRIMARY KEY NOT NULL,
  type            TEXT NOT NULL,
  card_id         INTEGER NOT NULL,

  expectation     TEXT NOT NULL,

  answered_l1     TEXT,
  answered_at     DATETIME,
  showed_mnemonic BOOLEAN,

  grade           TEXT
);
EOF

$GOPATH/bin/load-corpus-into-cards db/corpora/spanishpod.yaml db/db.sqlite3
#$GOPATH/bin/load-noun-cards db/1_nouns.csv db/db.sqlite3
