#!/bin/bash -ex

cd `dirname $0`/..

# Build Go first
cd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
go install -v bitbucket.org/danstutzman/language-learning-go/...

rm -f db/db.sqlite3
cat db/schema.sql | sqlite3 db/db.sqlite3

db/es-en-dictionary-from-anki-deck/load.sh

DB_PATH=./db/db.sqlite3 $GOPATH/bin/import-csv \
  db/dans-cards/morphemes.csv \
  db/dans-cards/cards.csv
