#!/bin/bash -ex
cd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
go install -v bitbucket.org/danstutzman/language-learning-go/...
HTTP_PORT=8080 DB_PATH=./db/db.sqlite3 \
  GOOGLE_TRANSLATE_API_KEY=`cat ~/.google_translate_api_key` \
  $GOPATH/bin/language-learning-go
