#!/bin/bash -ex
cd $GOPATH/src/bitbucket.org/danstutzman/language-learning-go
go vet bitbucket.org/danstutzman/language-learning-go/...
go install -v bitbucket.org/danstutzman/language-learning-go/...
HTTP_PORT=8080 DB_PATH=./db/db.sqlite3 \
  LANGUAGE_MODEL_PATH=db/language_model/es-20k.lm \
  $GOPATH/bin/language-learning-go
